run:
  timeout: "5m"
  tests: true
  allow-parallel-runners: true

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - "logs"

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic