app:
  name: "Whois API"
  version: "1.0.3"
  author: "Nopaleon Bonaparte"
  debug: true

service:
  http:
    host: ""
    port: 8001
    prefork: false
  redis:
    addr: "localhost:6379"
    DB: 0
    cache_enabled: true
  dns_resolver: "1.1.1.1:53"

rapidapi:
  enable_protection: false
  secret_key: ""

logger:
  level: "debug"
  report_caller: false
  format: "console"
  pretty_print: false

workerpool:
  size: 1500