name: 'whois-api'

services:
  app:
    container_name: 'whois-core'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE.REDIS.ADDR: host.docker.internal:6379
      SERVICE.HTTP.HOST: ""
      SERVICE.HTTP.PORT: 3000
      SERVICE.HTTP.PREFORK: false
      APP.DEBUG: false
      RAPIDAPI.ENABLE_PROTECTION: true
      RAPIDAPI.SECRET_KEY: 92a352a0-c638-11ef-a704-09571823e6ff
    ports:
      - "3001:3000"
    restart: on-failure

volumes:
  redis_data:
    driver: local